# Display clock with time 9:15

import turtle

turtle.showturtle()
turtle.exitonclick
turtle.circle(100)
turtle.penup()
turtle.goto(-90,97)
turtle.pendown()
turtle.write("9")
turtle.penup()
turtle.goto(90,97)
turtle.pendown()
turtle.write(3)
turtle.penup()
turtle.goto(-4,180)
turtle.pendown()
turtle.write(12)
turtle.penup()
turtle.goto(-3,5)
turtle.pendown()
turtle.write(6)
turtle.penup()
turtle.goto(0,100)
turtle.pendown()
turtle.right(7.5)
turtle.pensize(4)
turtle.backward(50)
turtle.goto(0,100)
turtle.left(7.5)
turtle.pensize(3)
turtle.forward(75)
turtle.goto(0,100)
turtle.left(90)
turtle.pensize(1)
turtle.forward(75)
turtle.penup()
turtle.goto(-20,-20)
turtle.pendown()
turtle.write("09:15:00")
turtle.exitonclick()

